### ISSUE TITLE
Permissions randomly revoked

### ISSUE THREAD

**Issue by flickPF94** [bluethefoxofficial/CreativePublicMessenger#4]
I cannot contribute to this repository, which is more updated than the creativesoftwareuk repository.

What happended? Is this going to be fixed? Can't i contribute to CPM?

**Comment by bluethefoxofficial** [comment]
It's a bug that I will be fixing shortly.

**Comment by bluethefoxofficial** [comment]
I essentially had to restart the csoftware one due to issues so I will need to read you and the csoftware one is now mainly just a backup.

**Comment by flickPF94** [comment]
"shortly"
huh
